web: java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap $JAVA_TOOL_OPTIONS -jar target/{{name}}.jar
{{#pgsql-hook?}}
release: JAVA_OPTS=$JAVA_TOOL_OPTIONS lein migrations migrate
{{/pgsql-hook?}}